# Generated by Django 5.0 on 2023-12-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food_type",
            name="choice",
        ),
        migrations.RemoveField(
            model_name="restaurant_type",
            name="choice",
        ),
        migrations.AddField(
            model_name="food_type",
            name="title",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="food_type",
            name="title_fa",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="restaurant_type",
            name="title",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="restaurant_type",
            name="title_fa",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
