# Generated by Django 5.0 on 2023-12-26 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_remove_food_type_choice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="types",
        ),
        migrations.AddField(
            model_name="food",
            name="types",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="places.food_type",
            ),
        ),
    ]
