# Generated by Django 5.0 on 2023-12-26 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_remove_food_types_food_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="types",
        ),
        migrations.AddField(
            model_name="food",
            name="food_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="places.food_type",
            ),
        ),
    ]
