# Generated by Django 5.0 on 2023-12-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0004_remove_food_types_food_food_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(),
        ),
    ]
