# Generated by Django 5.0 on 2023-12-28 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0005_alter_comment_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_created",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
