# Generated by Django 5.0 on 2023-12-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0006_comment_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="long_description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
