# Generated by Django 5.0 on 2023-12-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0007_place_long_description_alter_place_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="full_address",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="place",
            name="address",
            field=models.CharField(max_length=60),
        ),
    ]
