# Generated by Django 5.0 on 2023-12-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0008_place_full_address_alter_place_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="location_x",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="place",
            name="location_y",
            field=models.FloatField(),
        ),
    ]
